name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # - run: docker build -t bykolee1/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true bykolee1/react-test npm test
      - name: Run client tests
        run: |
          docker build -t bykolee1/react-test -f ./client/Dockerfile.dev ./client
          docker run --rm -e CI=true bykolee1/react-test npm test

      - name: Build and push client Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bykolee1/multi-client:latest
          platforms: linux/amd64
          file: ./client/Dockerfile
          context: ./client

      - name: Build and push nginx Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bykolee1/multi-nginx:latest
          platforms: linux/amd64
          file: ./nginx/Dockerfile
          context: ./nginx

      - name: Build and push server Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bykolee1/multi-server:latest
          platforms: linux/amd64
          file: ./server/Dockerfile
          context: ./server

      - name: Build and push worker Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bykolee1/multi-worker:latest
          platforms: linux/amd64
          file: ./worker/Dockerfile
          context: ./worker

      # - run: docker build -t rallycoding/multi-client ./client
      # - run: docker build -t rallycoding/multi-nginx ./nginx
      # - run: docker build -t rallycoding/multi-server ./server
      # - run: docker build -t rallycoding/multi-worker ./worker

      # - run: docker push rallycoding/multi-client
      # - run: docker push rallycoding/multi-nginx
      # - run: docker push rallycoding/multi-server
      # - run: docker push rallycoding/multi-worker

      - name: Generate deployment package
        run: zip -j deploy.zip Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          version_label: ${{ github.SHA }}
          region: ap-southeast-2
          deployment_package: deploy.zip
