name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # - run: docker build -t bykolee1/react-test -f ./client/Dockerfile.dev ./client
      # - run: docker run -e CI=true bykolee1/react-test npm test
      - name: Run client tests
        run: |
          docker build -t bykolee1/react-test -f ./client/Dockerfile.dev ./client
          docker run --rm -e CI=true bykolee1/react-test npm test

      - name: Build and push client Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          file: ./client/Dockerfile
          context: ./client
          tags: |
            bykolee1/multi-client:latest
            bykolee1/multi-client:${{ github.sha }}

      - name: Build and push server Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          file: ./server/Dockerfile
          context: ./server
          tags: |
            bykolee1/multi-server:latest
            bykolee1/multi-server:${{ github.sha }}

      - name: Build and push worker Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          file: ./worker/Dockerfile
          context: ./worker
          tags: |
            bykolee1/multi-worker:latest
            bykolee1/multi-worker:${{ github.sha }}

      # GKE 인증 설정 (Google 공식 방식)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          project_id: udemy-multi-k8s-474405
      
      # GKE 클러스터 인증 및 kubectl 자동 설정
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: multi-cluster
          location: asia-northeast2

      # k8s 디렉토리의 모든 설정 파일 적용
      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f k8s

      # Deployment 이미지 업데이트
      - name: Update deployment images
        run: |
          kubectl set image deployment/client-deployment client=bykolee1/multi-client:${{ github.sha }}
          kubectl set image deployment/server-deployment server=bykolee1/multi-server:${{ github.sha }}
          kubectl set image deployment/worker-deployment worker=bykolee1/multi-worker:${{ github.sha }}

      